interface CountryData {
  name: string
  greeting: string
}
export const CountryList: Record<string, CountryData> = {
  AF: { name: 'Afghanistan', greeting: 'سلام! خوش آمدید.' },
  AX: { name: 'Åland Islands', greeting: 'Hej! Välkommen.' },
  AL: { name: 'Albania', greeting: 'Përshëndetje! Mirë se vini.' },
  DZ: { name: 'Algeria', greeting: 'مرحبا! أهلاً بك.' },
  AS: { name: 'American Samoa', greeting: 'Hello! Welcome.' },
  AD: { name: 'Andorra', greeting: 'Hola! Benvingut.' },
  AO: { name: 'Angola', greeting: 'Olá! Bem-vindo.' },
  AI: { name: 'Anguilla', greeting: 'Hello! Welcome.' },
  AQ: { name: 'Antarctica', greeting: 'Hello! Welcome.' },
  AG: { name: 'Antigua and Barbuda', greeting: 'Hello! Welcome.' },
  AR: { name: 'Argentina', greeting: 'Hola! ¡Bienvenido!' },
  AM: { name: 'Armenia', greeting: 'Բարեւ! Բարի գալուստ.' },
  AW: { name: 'Aruba', greeting: 'Bon dia! Bon bini.' },
  AU: { name: 'Australia', greeting: "G'day! Welcome." },
  AT: { name: 'Austria', greeting: 'Servus! Willkommen.' },
  AZ: { name: 'Azerbaijan', greeting: 'Salam! Xoş gəlmisiniz.' },
  BS: { name: 'Bahamas', greeting: 'Hello! Welcome.' },
  BH: { name: 'Bahrain', greeting: 'مرحبا! أهلاً بك.' },
  BD: { name: 'Bangladesh', greeting: 'নমস্কার! স্বাগতম।' },
  BB: { name: 'Barbados', greeting: 'Hello! Welcome.' },
  BY: { name: 'Belarus', greeting: 'Вітаю! Сардэчна запрашаем.' },
  BE: { name: 'Belgium', greeting: 'Hallo! Welkom.' },
  BZ: { name: 'Belize', greeting: 'Hello! Welcome.' },
  BJ: { name: 'Benin', greeting: 'Bonjour! Bienvenue.' },
  BM: { name: 'Bermuda', greeting: 'Hello! Welcome.' },
  BT: { name: 'Bhutan', greeting: 'རྙེད་ནོར་ལ་བཀྲ་ཤིས་བདེ་ལེགས།' },
  BO: { name: 'Bolivia', greeting: '¡Hola! Bienvenido.' },
  BQ: { name: 'Bonaire, Sint Eustatius and Saba', greeting: 'Hello! Welcome.' },
  BA: { name: 'Bosnia and Herzegovina', greeting: 'Zdravo! Dobrodošli.' },
  BW: { name: 'Botswana', greeting: 'Dumela! Tswelopele.' },
  BR: { name: 'Brazil', greeting: 'Olá! Bem-vindo.' },
  IO: { name: 'British Indian Ocean Territory', greeting: 'Hello! Welcome.' },
  BN: {
    name: 'Brunei Darussalam',
    greeting: 'Selamat datang! Salam sejahtera.',
  },
  BG: { name: 'Bulgaria', greeting: 'Здравейте! Добре дошли.' },
  BF: { name: 'Burkina Faso', greeting: 'Bonjour! Bienvenue.' },
  BI: { name: 'Burundi', greeting: 'Bonjour! Bienvenue.' },
  KH: { name: 'Cambodia', greeting: 'ជំរាបសួរ! ស្វាគមន៍.' },
  CM: { name: 'Cameroon', greeting: 'Bonjour! Bienvenue.' },
  CA: { name: 'Canada', greeting: 'Hello! Welcome.' },
  CV: { name: 'Cape Verde', greeting: 'Olá! Bem-vindo.' },
  KY: { name: 'Cayman Islands', greeting: 'Hello! Welcome.' },
  CF: { name: 'Central African Republic', greeting: 'Bonjour! Bienvenue.' },
  TD: { name: 'Chad', greeting: 'مرحبا! أهلاً بك.' },
  CL: { name: 'Chile', greeting: '¡Hola! Bienvenido.' },
  CN: { name: 'China', greeting: '你好! 欢迎光临。' },
  CX: { name: 'Christmas Island', greeting: 'Hello! Welcome.' },
  CC: { name: 'Cocos (Keeling) Islands', greeting: 'Hello! Welcome.' },
  CO: { name: 'Colombia', greeting: '¡Hola! Bienvenido.' },
  KM: { name: 'Comoros', greeting: 'مرحبا! أهلاً بك.' },
  CG: { name: 'Congo', greeting: 'Bonjour! Bienvenue.' },
  CD: {
    name: 'Democratic Republic of the Congo',
    greeting: 'Bonjour! Bienvenue.',
  },
  CK: { name: 'Cook Islands', greeting: 'Kia Orana! Welcome.' },
  CR: { name: 'Costa Rica', greeting: '¡Hola! Bienvenido.' },
  CI: { name: "Côte d'Ivoire", greeting: 'Bonjour! Bienvenue.' },
  HR: { name: 'Croatia', greeting: 'Bok! Dobrodošli.' },
  CU: { name: 'Cuba', greeting: '¡Hola! Bienvenido.' },
  CW: { name: 'Curaçao', greeting: 'Bon dia! Bon bini.' },
  CY: { name: 'Cyprus', greeting: 'Γεια σας! Καλώς ήρθατε.' },
  CZ: { name: 'Czech Republic', greeting: 'Dobrý den! Vítejte.' },
  DK: { name: 'Denmark', greeting: 'Hej! Velkommen.' },
  DJ: { name: 'Djibouti', greeting: 'مرحبا! أهلاً بك.' },
  DM: { name: 'Dominica', greeting: 'Hello! Welcome.' },
  DO: { name: 'Dominican Republic', greeting: '¡Hola! Bienvenido.' },
  EC: { name: 'Ecuador', greeting: '¡Hola! Bienvenido.' },
  EG: { name: 'Egypt', greeting: 'مرحبا! أهلاً بك.' },
  SV: { name: 'El Salvador', greeting: '¡Hola! Bienvenido.' },
  GQ: { name: 'Equatorial Guinea', greeting: '¡Hola! Bienvenido.' },
  ER: { name: 'Eritrea', greeting: 'ሰላም! እንዴት ነሽ?' },
  EE: { name: 'Estonia', greeting: 'Tere! Tere tulemast.' },
  ET: { name: 'Ethiopia', greeting: 'ሰላም! እንዴት ነሽ?' },
  FK: { name: 'Falkland Islands (Malvinas)', greeting: 'Hello! Welcome.' },
  FO: { name: 'Faroe Islands', greeting: 'Hallo! Velkominn.' },
  FJ: { name: 'Fiji', greeting: 'Bula! Welcome.' },
  FI: { name: 'Finland', greeting: 'Hei! Tervetuloa.' },
  FR: { name: 'France', greeting: 'Bonjour! Bienvenue.' },
  GF: { name: 'French Guiana', greeting: 'Bonjour! Bienvenue.' },
  PF: { name: 'French Polynesia', greeting: 'Bonjour! Bienvenue.' },
  TF: { name: 'French Southern Territories', greeting: 'Hello! Welcome.' },
  GA: { name: 'Gabon', greeting: 'Bonjour! Bienvenue.' },
  GM: { name: 'Gambia', greeting: 'Hello! Welcome.' },
  GE: { name: 'Georgia', greeting: 'გამარჯობა! მოგესალმებით.' },
  DE: { name: 'Germany', greeting: 'Hallo! Willkommen.' },
  GH: { name: 'Ghana', greeting: 'Hello! Welcome.' },
  GI: { name: 'Gibraltar', greeting: 'Hello! Welcome.' },
  GR: { name: 'Greece', greeting: 'Γεια σας! Καλώς ήρθατε.' },
  GL: { name: 'Greenland', greeting: 'Aluu! Takuss.' },
  GD: { name: 'Grenada', greeting: 'Hello! Welcome.' },
  GP: { name: 'Guadeloupe', greeting: 'Hello! Welcome.' },
  GU: { name: 'Guam', greeting: 'Hello! Welcome.' },
  GT: { name: 'Guatemala', greeting: '¡Hola! Bienvenido.' },
  GG: { name: 'Guernsey', greeting: 'Hello! Welcome.' },
  GN: { name: 'Guinea', greeting: 'Bonjour! Bienvenue.' },
  GW: { name: 'Guinea-Bissau', greeting: 'Olá! Bem-vindo.' },
  GY: { name: 'Guyana', greeting: 'Hello! Welcome.' },
  HT: { name: 'Haiti', greeting: 'Bonjour! Bienvenue.' },
  HN: { name: 'Honduras', greeting: '¡Hola! Bienvenido.' },
  HK: { name: 'Hong Kong', greeting: '你好! 歡迎光臨。' },
  HU: { name: 'Hungary', greeting: 'Szia! Üdvözöljük.' },
  IS: { name: 'Iceland', greeting: 'Halló! Velkominn.' },
  IN: { name: 'India', greeting: 'नमस्ते! स्वागतम्।' },
  ID: { name: 'Indonesia', greeting: 'Halo! Selamat datang.' },
  IR: { name: 'Iran (Islamic Republic of)', greeting: 'سلام! خوش آمدید.' },
  IQ: { name: 'Iraq', greeting: 'مرحبا! أهلاً بك.' },
  IE: { name: 'Ireland', greeting: 'Dia dhuit! Fáilte.' },
  IM: { name: 'Isle of Man', greeting: 'Hello! Welcome.' },
  IL: { name: 'Israel', greeting: 'שלום! ברוכים הבאים.' },
  IT: { name: 'Italy', greeting: 'Ciao! Benvenuto.' },
  JM: { name: 'Jamaica', greeting: 'Hello! Welcome.' },
  JP: { name: 'Japan', greeting: 'こんにちは! ようこそ。' },
  JE: { name: 'Jersey', greeting: 'Hello! Welcome.' },
  JO: { name: 'Jordan', greeting: 'مرحبا! أهلاً بك.' },
  KZ: { name: 'Kazakhstan', greeting: 'Сәлеметсіз бе! Қош келдіңіз.' },
  KE: { name: 'Kenya', greeting: 'Jambo! Karibu.' },
  KI: { name: 'Kiribati', greeting: 'Mauri! Welcome.' },
  KP: {
    name: "Korea (Democratic People's Republic of)",
    greeting: '안녕하세요! 환영합니다.',
  },
  KR: { name: 'Korea (Republic of)', greeting: '안녕하세요! 환영합니다.' },
  KW: { name: 'Kuwait', greeting: 'مرحبا! أهلاً بك.' },
  KG: { name: 'Kyrgyzstan', greeting: 'Саламатсызбы? Кош келиниз.' },
  LA: {
    name: "Lao People's Democratic Republic",
    greeting: 'ສະບາຍດີ! ຍິນດີຕ້ອນຮັບ.',
  },
  LV: { name: 'Latvia', greeting: 'Sveiki! Laipni lūdzam.' },
  LB: { name: 'Lebanon', greeting: 'مرحبا! أهلاً بك.' },
  LS: { name: 'Lesotho', greeting: 'Hello! Welcome.' },
  LR: { name: 'Liberia', greeting: 'Hello! Welcome.' },
  LY: { name: 'Libya', greeting: 'مرحبا! أهلاً بك.' },
  LI: { name: 'Liechtenstein', greeting: 'Hallo! Willkommen.' },
  LT: { name: 'Lithuania', greeting: 'Labas! Sveiki atvykę.' },
  LU: { name: 'Luxembourg', greeting: 'Moien! Wëllkomm.' },
  MO: { name: 'Macao', greeting: 'Hello! Welcome.' },
  MK: { name: 'North Macedonia', greeting: 'Здраво! Добредојдовте.' },
  MG: { name: 'Madagascar', greeting: 'Manao ahoana! Tonga soa.' },
  MW: { name: 'Malawi', greeting: 'Moni! Mwalandiridwa.' },
  MY: { name: 'Malaysia', greeting: 'Hello! Selamat datang.' },
  MV: {
    name: 'Maldives',
    greeting: 'އަދި ދުވަސްކޮޅު! މޫގުހުން ވަނައަމީހަކަން.',
  },
  ML: { name: 'Mali', greeting: 'Bonjour! Bienvenue.' },
  MT: { name: 'Malta', greeting: 'Hello! Merħba.' },
  MH: { name: 'Marshall Islands', greeting: 'Yokwe! Kommol tata.' },
  MQ: { name: 'Martinique', greeting: 'Hello! Welcome.' },
  MR: { name: 'Mauritania', greeting: 'مرحبا! أهلاً بك.' },
  MU: { name: 'Mauritius', greeting: 'Hello! Welcome.' },
  YT: { name: 'Mayotte', greeting: 'Hello! Welcome.' },
  MX: { name: 'Mexico', greeting: '¡Hola! Bienvenido.' },
  FM: { name: 'Micronesia (Federated States of)', greeting: 'Hello! Welcome.' },
  MD: { name: 'Moldova (Republic of)', greeting: 'Bună! Bine ați venit.' },
  MC: { name: 'Monaco', greeting: 'Bonjour! Bienvenue.' },
  MN: { name: 'Mongolia', greeting: 'Сайн байна уу? Тавтай морил.' },
  ME: { name: 'Montenegro', greeting: 'Zdravo! Dobrodošli.' },
  MS: { name: 'Montserrat', greeting: 'Hello! Welcome.' },
  MA: { name: 'Morocco', greeting: 'مرحبا! أهلاً بك.' },
  MZ: { name: 'Mozambique', greeting: 'Olá! Bem-vindo.' },
  MM: { name: 'Myanmar', greeting: 'မင်္ဂလာပါ! ကြိုဆိုပါတယ်။' },
  NA: { name: 'Namibia', greeting: 'Hello! Welcome.' },
  NR: { name: 'Nauru', greeting: 'Hello! Welcome.' },
  NP: { name: 'Nepal', greeting: 'नमस्ते! स्वागतम्।' },
  NL: { name: 'Netherlands', greeting: 'Hallo! Welkom.' },
  NC: { name: 'New Caledonia', greeting: 'Bonjour! Bienvenue.' },
  NZ: { name: 'New Zealand', greeting: ' Kia ora! Nau mai haere mai' },
  NI: { name: 'Nicaragua', greeting: '¡Hola! Bienvenido.' },
  NE: { name: 'Niger', greeting: 'Bonjour! Bienvenue.' },
  NG: { name: 'Nigeria', greeting: 'Hello! Welcome.' },
  NU: { name: 'Niue', greeting: 'Fakaalofa lahi atu! Welcome.' },
  NF: { name: 'Norfolk Island', greeting: 'Hello! Welcome.' },
  MP: { name: 'Northern Mariana Islands', greeting: 'Hello! Welcome.' },
  NO: { name: 'Norway', greeting: 'Hei! Velkommen.' },
  OM: { name: 'Oman', greeting: 'مرحبا! أهلاً بك.' },
  PK: { name: 'Pakistan', greeting: 'ہیلو! خوش آمدید۔' },
  PW: { name: 'Palau', greeting: 'Alii! Uelu rebwel.' },
  PS: { name: 'Palestine, State of', greeting: 'مرحبا! أهلاً بك.' },
  PA: { name: 'Panama', greeting: '¡Hola! Bienvenido.' },
  PG: { name: 'Papua New Guinea', greeting: 'Hello! Welcome.' },
  PY: { name: 'Paraguay', greeting: '¡Hola! Bienvenido.' },
  PE: { name: 'Peru', greeting: '¡Hola! Bienvenido.' },
  PH: { name: 'Philippines', greeting: 'Kumusta! Maligayang pagdating.' },
  PN: { name: 'Pitcairn', greeting: 'Hello! Welcome.' },
  PL: { name: 'Poland', greeting: 'Cześć! Witamy.' },
  PT: { name: 'Portugal', greeting: 'Olá! Bem-vindo.' },
  PR: { name: 'Puerto Rico', greeting: '¡Hola! Bienvenido.' },
  QA: { name: 'Qatar', greeting: 'مرحبا! أهلاً بك.' },
  RE: { name: 'Réunion', greeting: 'Hello! Welcome.' },
  RO: { name: 'Romania', greeting: 'Salut! Bine ați venit.' },
  RU: { name: 'Russian Federation', greeting: 'Привет! Добро пожаловать.' },
  RW: { name: 'Rwanda', greeting: 'Hello! Welcome.' },
  BL: { name: 'Saint Barthélemy', greeting: 'Hello! Welcome.' },
  SH: {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    greeting: 'Hello! Welcome.',
  },
  KN: { name: 'Saint Kitts and Nevis', greeting: 'Hello! Welcome.' },
  LC: { name: 'Saint Lucia', greeting: 'Hello! Welcome.' },
  MF: { name: 'Saint Martin (French part)', greeting: 'Hello! Welcome.' },
  PM: { name: 'Saint Pierre and Miquelon', greeting: 'Hello! Welcome.' },
  VC: { name: 'Saint Vincent and the Grenadines', greeting: 'Hello! Welcome.' },
  WS: { name: 'Samoa', greeting: 'Hello! Welcome.' },
  SM: { name: 'San Marino', greeting: 'Ciao! Benvenuto.' },
  ST: { name: 'Sao Tome and Principe', greeting: 'Olá! Bem-vindo.' },
  SA: { name: 'Saudi Arabia', greeting: 'مرحبا! أهلاً بك.' },
  SN: { name: 'Senegal', greeting: 'Bonjour! Bienvenue.' },
  RS: { name: 'Serbia', greeting: 'Здраво! Добродошли.' },
  SC: { name: 'Seychelles', greeting: 'Hello! Welcome.' },
  SL: { name: 'Sierra Leone', greeting: 'Hello! Welcome.' },
  SG: { name: 'Singapore', greeting: 'Hello! Welcome.' },
  SX: { name: 'Sint Maarten (Dutch part)', greeting: 'Hello! Welcome.' },
  SK: { name: 'Slovakia', greeting: 'Dobrý deň! Vitajte.' },
  SI: { name: 'Slovenia', greeting: 'Zdravo! Dobrodošli.' },
  SB: { name: 'Solomon Islands', greeting: 'Hello! Welcome.' },
  SO: { name: 'Somalia', greeting: 'Hello! Welcome.' },
  ZA: { name: 'South Africa', greeting: 'Hello! Welcome.' },
  GS: {
    name: 'South Georgia and the South Sandwich Islands',
    greeting: 'Hello! Welcome.',
  },
  SS: { name: 'South Sudan', greeting: 'Hello! Welcome.' },
  ES: { name: 'Spain', greeting: 'Hola! Bienvenido.' },
  LK: { name: 'Sri Lanka', greeting: 'ආයුබෝවන්! සාදරයෙන් පිළිගනිමු.' },
  SD: { name: 'Sudan', greeting: 'مرحبا! أهلاً بك.' },
  SR: { name: 'Suriname', greeting: 'Hello! Welcome.' },
  SJ: { name: 'Svalbard and Jan Mayen', greeting: 'Hello! Welcome.' },
  SZ: { name: 'Eswatini', greeting: 'Hello! Welcome.' },
  SE: { name: 'Sweden', greeting: 'Hej! Välkommen.' },
  CH: { name: 'Switzerland', greeting: 'Hallo! Willkommen.' },
  SY: { name: 'Syrian Arab Republic', greeting: 'مرحبا! أهلاً بك.' },
  TW: { name: 'Taiwan', greeting: '你好! 歡迎光臨。' },
  TJ: { name: 'Tajikistan', greeting: 'Салом! Хуш омадед.' },
  TZ: { name: 'Tanzania, United Republic of', greeting: 'Hello! Welcome.' },
  TH: { name: 'Thailand', greeting: 'สวัสดีครับ! ยินดีต้อนรับครับ.' },
  TL: { name: 'Timor-Leste', greeting: 'Ola! Bem-vindo.' },
  TG: { name: 'Togo', greeting: 'Bonjour! Bienvenue.' },
  TK: { name: 'Tokelau', greeting: 'Talofa! Fakatalofa atu.' },
  TO: { name: 'Tonga', greeting: 'Mālō e lelei! Welcome.' },
  TT: { name: 'Trinidad and Tobago', greeting: 'Hello! Welcome.' },
  TN: { name: 'Tunisia', greeting: 'مرحبا! أهلاً بك.' },
  TR: { name: 'Turkey', greeting: 'Merhaba! Hoş geldiniz.' },
  TM: { name: 'Turkmenistan', greeting: 'Salam! Hoş geldiňiz.' },
  TC: { name: 'Turks and Caicos Islands', greeting: 'Hello! Welcome.' },
  TV: { name: 'Tuvalu', greeting: 'Talofa! Welcome.' },
  UG: { name: 'Uganda', greeting: 'Hello! Welcome.' },
  UA: { name: 'Ukraine', greeting: 'Вітаю! Ласкаво просимо.' },
  AE: { name: 'United Arab Emirates', greeting: 'مرحبا! أهلاً بك.' },
  GB: {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    greeting: 'Hello! Welcome.',
  },
  UM: {
    name: 'United States Minor Outlying Islands',
    greeting: 'Hello! Welcome.',
  },
  US: {
    name: 'United States of America',
    greeting: 'Hello! Welcome.',
  },
  UY: { name: 'Uruguay', greeting: '¡Hola! Bienvenido.' },
  UZ: { name: 'Uzbekistan', greeting: 'Salom! Xush kelibsiz.' },
  VU: { name: 'Vanuatu', greeting: 'Halo! Welkam.' },
  VE: {
    name: 'Venezuela (Bolivarian Republic of)',
    greeting: '¡Hola! Bienvenido.',
  },
  VN: { name: 'Viet Nam', greeting: 'Xin chào! Chào mừng bạn.' },
  VG: { name: 'Virgin Islands (British)', greeting: 'Hello! Welcome.' },
  VI: { name: 'Virgin Islands (U.S.)', greeting: 'Hello! Welcome.' },
  WF: { name: 'Wallis and Futuna', greeting: 'Bonjour! Bienvenue.' },
  EH: { name: 'Western Sahara', greeting: 'مرحبا! أهلاً بك.' },
  YE: { name: 'Yemen', greeting: 'مرحبا! أهلاً بك.' },
  ZM: { name: 'Zambia', greeting: 'Hello! Welcome.' },
  ZW: { name: 'Zimbabwe', greeting: 'Hello! Welcome.' },
}
